default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER") { ENV['USER'] } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  <<: *default
  database: habitkit_development

test:
  <<: *default
  database: habitkit_test

production:
  <<: *default
  database: habitkit_production
  username: habitkit
  password: <%= ENV['HABITKIT_DATABASE_PASSWORD'] %>

