default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: habitkit_development

test:
  <<: *default
  database: habitkit_test

production:
  <<: *default
  database: habitkit_production
  username: habitkit
  password: <%= ENV.fetch("DATABASE_PASSWORD", "habitkit_dev") %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
